import Head from "next/head";
import styles from "../styles/Home.module.css";
import Weather_Today from "./components/Weather_Today";
import Weather_Week from "./components/Weather_Week";

export default function Home() {
  
  const apikey = process.env.REACT_APP_API_KEY_1;
  
  
  return (
    <>
      <Head>
        <title>Weather-Lytics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-full bg-red-400 flex flex-col lg:flex-row">
        <div className="bg-blue-300 w-full lg:w-1/4 lg:h-full">
          <Weather_Today apikey={apikey}/>
        </div>
        <div className="bg-green-500 w-full lg:h-full ">
          < Weather_Week apikey={apikey}/>
        </div>
      </div>
    </>
  );
}
